# Generated by Django 4.0 on 2022-03-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_comment_author_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.CharField(default='asds', max_length=64),
        ),
    ]
