# Generated by Django 4.0.2 on 2022-04-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_comment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('course_id', models.IntegerField()),
            ],
        ),
    ]
