# Generated by Django 4.0 on 2022-03-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_comment_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.IntegerField(null=True),
        ),
    ]
