# Generated by Django 4.0 on 2022-04-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_learning'),
        ('main', '0013_remove_comment_parent'),
    ]

    operations = [
    ]
