# Generated by Django 4.0 on 2022-04-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_merge_0008_learning_0013_remove_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='liked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
