# Generated by Django 4.0 on 2022-04-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0016_alter_course_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='liked',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
