# Generated by Django 4.0 on 2022-04-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_course_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='liked',
            new_name='like',
        ),
    ]
