# Generated by Django 4.0 on 2022-04-03 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0019_alter_course_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='like',
        ),
        migrations.AddField(
            model_name='course',
            name='liked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
