# Generated by Django 4.0 on 2022-04-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_course_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='liked',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
