# Generated by Django 4.0 on 2022-04-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_course_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='liked',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
