# Generated by Django 4.0 on 2022-04-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_course_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='liked',
        ),
    ]
