# Generated by Django 4.0 on 2022-04-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_course_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='added',
        ),
    ]
