# Generated by Django 4.0 on 2022-04-03 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0027_remove_course_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='added',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
