# Generated by Django 4.0 on 2022-04-03 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0029_alter_course_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='added',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
