# Generated by Django 4.0 on 2022-04-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_course_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='liked',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
