# Generated by Django 4.0 on 2022-04-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_comment_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='liked',
        ),
    ]
