# Generated by Django 4.0 on 2022-04-09 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0034_comment_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dis',
            field=models.ManyToManyField(related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
