# Generated by Django 4.0.2 on 2022-04-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_delete_learning_course_learn_user_alter_course_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.ImageField(default='main/img.jpeg', upload_to='course_images'),
            preserve_default=False,
        ),
    ]
